src/objects/Queue_Item__c.object
<CustomObject>
    <fields>
        <fullName>Job_Id__c</fullName>
        <externalId>true</externalId>
        <label>Job Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Queue Item</label>
    <nameField>
        <displayFormat>QI-{0}</displayFormat>
        <label>Queue Item name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queue Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SendMessageToContactBatch.cls
public with sharing class SendMessageToContactBatch implements Database.Batchable<SendMessageToContactQueue.MessageDetails>, Database.AllowsCallouts {

	private List<SendMessageToContactQueue.MessageDetails> bItems;
	private Id jId;

	public SendMessageToContactBatch(List<SendMessageToContactQueue.MessageDetails> MessageDetailss, Id jobId){
		this.bItems = MessageDetailss;
		this.jId = jobId;
	}	

	public Iterable<SendMessageToContactQueue.MessageDetails> start(Database.BatchableContext con){
		return this.bItems;
	}

	public void execute(Database.BatchableContext con, List<SendMessageToContactQueue.MessageDetails> items){

		SendMessageToContactQueue messageProcessor = new SendMessageToContactQueue();

		for(SendMessageToContactQueue.MessageDetails bItem : items){
			messageProcessor.processMessageDetails(bItem);
		}

	}

	public void finish(Database.BatchableContext con){
		delete [SELECT Id FROM Queue_Item__c WHERE Job_Id__c = :jId];
	}

}